title: Students@Systems

logo: /assets/img/logo.png
title-below-logo: false
email: contact@students-at-systems.org

description:
show_downloads: false
theme: jekyll-theme-minimal

include:
  - pages

colors:
  theme: 228B22
  theme-light: 4CBB17
  theme-dark: 355E3B
